### ISSUE TITLE
set-serviceprincipal.ps1 "CSEO DevOps Role" is a custom role and not present in other ADs

### ISSUE THREAD

**Issue by csando** [microsoftgraph/group-membership-management#13]
**Describe the bug**
This role is assigned by the script however it is a custom role. Causes script to fail

**To Reproduce**
Run set-serviceprincipal.ps1 on a tenant other than the author's

**Comment by pauldalyii-msft** [comment]
Thanks for bringing this to our attention.  We have removed this reference from the scripts.
