### ISSUE TITLE
'BackupEntity' does not contain a constructor that takes 2 arguments - AzureBlobBackupRepository.cs, AzureTableBackupRepository.cs

### ISSUE THREAD

**Issue by DG-RMD** [microsoftgraph/group-membership-management#15]
Encountering a problem when running a pipeline, it looks like a constructor issue?  Any thoughts/idea appreciated

Service\GroupMembershipManagement\Repositories.AzureBlobBackupRepository\AzureBlobBackupRepository.cs(108,27):   Error CS1729: 'BackupEntity' does not contain a constructor that takes 2 arguments
--
Service\GroupMembershipManagement\Repositories.AzureTableBackupRepository\AzureTableBackupRepository.cs(49,47):   Error CS1729: 'BackupEntity' does not contain a constructor that takes 2 arguments

**Comment by DG-RMD** [comment]
The BackupEntity class has no constructors, but is being called for the 2-arg constructor

https://github.com/microsoftgraph/group-membership-management/blob/master/Service/GroupMembershipManagement/Entities/AzureTableBackup/BackupEntity.cs

**Comment by alrios-ms** [comment]
Hi @DG-RMD ,

You are right, looks like there was an issue with the previous push, we will look into this.

Regards.

**Comment by alrios-ms** [comment]
Code has been updated.
