### ISSUE TITLE
is the only possible way SecurityGroup -> OfficeGroup

### ISSUE THREAD

**Issue by dborchers-gc** [microsoftgraph/group-membership-management#24]
Would it be possible to sync members from OfficeGroup to OfficeGroup?

Adding OfficeGroup as Source seems to be a problem:
![image](https://user-images.githubusercontent.com/63800439/184476702-51c3f536-a3d5-4cdf-800c-cb5933b4f776.png)

**Comment by pauldalyii-msft** [comment]
An office group as a source is a supported scenario.  In fact, in some scenarios, we use the destination as another source group so that members added directly to the destination aren't removed.

I'd guess is that there is something else that is making the query column invalid.  Do you mind double-checking the guid that represents that office group?

**Comment by dborchers-gc** [comment]
It’s all solved I had the wrong query syntax. It’s not easy to understand in your documentation on the one side to write about ; as separator and on the other side you have examples with , as separator but it’s ,

I’ll try to make a PR for that

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Paul Daly (MSFT) ***@***.***>
Gesendet: Tuesday, August 16, 2022 7:25:18 PM
An: microsoftgraph/group-membership-management ***@***.***>
Cc: Daniel Remmers ***@***.***>; State change ***@***.***>
Betreff: Re: [microsoftgraph/group-membership-management] is the only possible way SecurityGroup -> OfficeGroup (Issue #24)


An office group as a source is a supported scenario. In fact, in some scenarios, we use the destination as another source group so that members added directly to the destination aren't removed.

I'd guess is that there is something else that is making the query column invalid. Do you mind double-checking the guid that represents that office group?
