### ISSUE TITLE
Question: Get SourceGroup from Logs

### ISSUE THREAD

**Issue by dborchers-gc** [microsoftgraph/group-membership-management#26]
Over the Log Analytics i can get some informations how the gmm works but i missed some.

Example:
I have 2 groups (A, B) and want to sync the members to a third group (C)

A - contains 3 members
B - contains 6 members

after first run the group C contains 9 members

now i add 2 members to group A and 1 to group B, after the next sync my group C has 13 members but i dont really found a way in the logs to see how much users come from which source.

Do oyu have an idea?

**Comment by alrios-ms** [comment]
@dborchers-gc You can find that information using this query:

ApplicationLog_CL 
| where Message startswith "From group"
| project TimeGenerated, location_s, TargetOfficeGroupId_g, Message
| order by TimeGenerated asc

You should see something like "From group <group-id>, read <user-count> users ..."

**Comment by dborchers-gc** [comment]
Okay I know this entries but I don’t see how much users come from this source

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: alrios-ms ***@***.***>
Gesendet: Tuesday, August 16, 2022 6:40:12 PM
An: microsoftgraph/group-membership-management ***@***.***>
Cc: Daniel Remmers ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/group-membership-management] Question: Get SourceGroup from Logs (Issue #26)


@dborchers-gc<https://github.com/dborchers-gc> You can find that information using this query:

ApplicationLog_CL
| where Message startswith "From group"
| project TimeGenerated, location_s, TargetOfficeGroupId_g, Message
| order by TimeGenerated asc

You should see something like "From group , read users ..."

**Comment by dborchers-gc** [comment]
The number of users in the entries are the whole members count, i´m searching for the difference

**Comment by alrios-ms** [comment]
I see, currently we don't track the deltas for individual sources.

**Comment by dborchers-gc** [comment]
@alrios-ms Maybe you can add it to the wishlist for next update ;-)

**Comment by alrios-ms** [comment]
@dborchers-gc I'll bring this request to the team!

Also, we would like to understand your use case for GMM, how you are planning to use it, is it for personal use or to manage your company groups, how many groups are you planning to manage, is there any feature you would like to see added to GMM? 

If you feel comfortable sharing any of that information you can reach out to us via GMMFeedback@service.microsoft.com

Regards.

**Comment by dborchers-gc** [comment]
Oh great idea I think you should see my solution live 😉 I will send you a mail tomorrow

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: alrios-ms ***@***.***>
Gesendet: Wednesday, August 17, 2022 5:30:37 PM
An: microsoftgraph/group-membership-management ***@***.***>
Cc: Daniel Remmers ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/group-membership-management] Question: Get SourceGroup from Logs (Issue #26)


@dborchers-gc<https://github.com/dborchers-gc> I'll bring this request to the team!

Also, we would like to understand your use case for GMM, how you are planning to use it, is it for personal use or to manage your company groups, how many groups are you planning to manage, is there any feature you would like to see added to GMM?

If you feel comfortable sharing any of that information you can reach out to us via ***@***.******@***.***>

Regards.

**Comment by dborchers-gc** [comment]
hey @alrios-ms i can't send a mail to the adress, maybe ist not setup for external senders?

**Comment by dborchers-gc** [comment]
If you like send me a mail to daniel.remmers@gc-gruppe.de

**Comment by alrios-ms** [comment]
Oh sorry about that, we will fix that issue with the email account.
