### ISSUE TITLE
How to use & install the WebUI

### ISSUE THREAD

**Issue by dborchers-gc** [microsoftgraph/group-membership-management#27]
In the project files there is a folder for a WebUI but in the installation process is no point how to install that? Is it possible to use it? how does it work?

**Comment by alrios-ms** [comment]
@dborchers-gc It is still a work in progress, currently it does not provide any functionality to see or manage your GMM-managed groups. This is how it looks right now, which might change in the future.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/70599097/185444752-818f744b-0576-49ba-88d1-e87b85416b81.png">
