### ISSUE TITLE
Successful Deployment but no jobtable

### ISSUE THREAD

**Issue by dborchers-gc** [microsoftgraph/group-membership-management#34]
Hello, ive deployed the gmm in a new environemnt and after some start-issues th deployment was finished but i have no jobtable in the depending on Storage-Account, any idea?

Here are the Logs:
[logs_38.zip](https://github.com/microsoftgraph/group-membership-management/files/10401458/logs_38.zip)

**Comment by alrios-ms** [comment]
Hi @dborchers-gc,

The jobs table is not created as part of the deployment, it is created the first time JobTrigger function runs.

If for some reason the table is not created even after running JobTrigger, it is possible to create it from the Azure Portal.

![image](https://user-images.githubusercontent.com/70599097/214719997-a9f8cf4b-4970-4a80-ba50-470c3f06817b.png)
